# WHM Plugin Registration
# Location: /usr/local/cpanel/whostmgr/conf/whmplugins/supervisormanager.conf
#
# Reference: https://api.docs.cpanel.net/guides/guide-to-whm-plugins/

WHMModule=supervisormanager
name=Supervisor Manager
icon=plugin-icons/supervisormanager.svg
group=cPanel
order=400
url=../cgi/supervisormanager/index.cgi
acl=all
acl_user_access=1
